name = "youtube-notify"
main = "src/worker.js"
compatibility_date = "2026-09-01"
[triggers]
crons = ["0 0 */4 * *"]
[[kv_namespaces]]
binding = "SEEN_VIDEOS"
id = "d0b24a23f4234fceb30afc7da805aaeb"
[vars]
YOUTUBE_CHANNEL_ID = "UCosfmChhKwrbK9WDnDuYAWQ"
